# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import django.core.validators
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CancerCase',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, verbose_name='ID', primary_key=True)),
                ('group', models.IntegerField(blank=True, choices=[(0, 'Control group'), (1, 'Treatment group')], null=True, verbose_name='Group')),
                ('id_for_hospital', models.IntegerField(blank=True, null=True, verbose_name='Id for hospital')),
                ('id_for_doctor', models.IntegerField(blank=True, null=True, verbose_name='Id for doctor')),
                ('organ', models.CharField(max_length=16)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClipsCase',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, verbose_name='ID', primary_key=True)),
                ('group', models.IntegerField(blank=True, choices=[(0, 'Control group'), (1, 'Treatment group')], null=True, verbose_name='Group')),
                ('id_for_hospital', models.IntegerField(blank=True, null=True, verbose_name='Id for hospital')),
                ('id_for_doctor', models.IntegerField(blank=True, null=True, verbose_name='Id for doctor')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('age', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Age', null=True)),
                ('age_interval', models.IntegerField(blank=True, choices=[(1, '< 60'), (2, '60-74'), (3, '>= 75')], null=True, verbose_name='Age interval', max_length=2)),
                ('sex', models.IntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female')], null=True, verbose_name='Sex', max_length=1)),
                ('asa', models.IntegerField(blank=True, choices=[(1, 'I'), (2, 'II'), (3, 'III'), (4, 'IV')], null=True, verbose_name='ASA')),
                ('hypertension', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Hypertension')),
                ('hb', models.FloatField(blank=True, null=True, verbose_name='HB (g/dL)')),
                ('platelets', models.IntegerField(blank=True, null=True, verbose_name='Platelets (x10⁹/L)')),
                ('inr', models.FloatField(blank=True, null=True, verbose_name='INR')),
                ('pt', models.IntegerField(blank=True, null=True, verbose_name='PT (s)')),
                ('aspirin', models.IntegerField(blank=True, choices=[(0, 'No'), (1, '100mg cease'), (2, '300mg cease'), (3, '100mg during EMR'), (4, '300mg during EMR')], null=True, verbose_name='Aspirin')),
                ('anticoagulants', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Aspirin'), (2, 'Clopidogrel'), (3, 'Other antiagregant'), (4, 'Warfarin'), (5, 'NSAID'), (6, '2 NSAID including aspiring or not'), (7, 'Aspirin+clopidogrel'), (8, 'NACOs')], null=True, verbose_name='Anticoagulants')),
                ('heparinbridgetherapy', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Heparin Bridge Therapy')),
                ('nombre_p_activo_antiagreg_anticoag', models.IntegerField(blank=True, null=True, verbose_name='Active ingredients anticoagulant/antiagregant')),
                ('day_of_reintroduction_antiagregant', models.IntegerField(blank=True, null=True, verbose_name='Day of reintroduction anticoagulant/antiagregant')),
                ('paris_calif', models.IntegerField(blank=True, choices=[(1, '0Is'), (2, '0IIa'), (3, '0IIa+0Is'), (4, '0Is+0IIa'), (5, '0IIb'), (6, '0IIc'), (7, '0IIa+0IIc'), (8, '0IIb+0IIc'), (9, '0IIb+0IIa')], null=True, verbose_name='Paris Clasif.')),
                ('lst_yn', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='LST yn')),
                ('lst_morphology', models.IntegerField(blank=True, choices=[(1, 'Granular homogeneous'), (2, 'Focal nodular mixed type'), (3, 'Whole nodular mixed type'), (4, 'Flat elevated'), (5, 'Psudodepressed')], null=True, verbose_name='LST Morphology')),
                ('large_nodule_one_cm', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Large nodule 1cm')),
                ('demacrated_depressed_area', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Demacrated depressed area')),
                ('sclerous_wall_change', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Sclerous wall change')),
                ('fold_convergency', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Fold convergency')),
                ('chicken_skin_mucosa_around', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Chicken skin mucosa around')),
                ('maximum_size_mm', models.IntegerField(blank=True, null=True, verbose_name='Maximum size (mm)')),
                ('area_square_cm', models.IntegerField(blank=True, null=True, verbose_name='Area (cm2)')),
                ('location', models.IntegerField(blank=True, choices=[(1, 'Rectum'), (2, 'Left colon'), (3, 'Splenic flexure'), (4, 'Transverse'), (5, 'Hepatic'), (6, 'Ascendent'), (7, 'Cecum')], null=True, verbose_name='Location')),
                ('ileocecal_valve_involvement', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Ileocecal valve involvement')),
                ('high_definition', models.IntegerField(blank=True, choices=[(1, 'Conventional endoscope'), (2, 'High definition'), (3, 'Optic magnification')], null=True, verbose_name='High definition')),
                ('endoscopemodel', models.CharField(blank=True, null=True, verbose_name='Endoscope model', max_length=50)),
                ('nbi', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='NBI')),
                ('nbi_sano', models.IntegerField(blank=True, choices=[(1, 'I'), (2, 'II'), (3, 'IIIA'), (4, 'IIIB')], null=True, verbose_name='NBI sano')),
                ('nbi_nice', models.IntegerField(blank=True, choices=[(1, 'Type 1'), (2, 'Type 2'), (3, 'Type 3')], null=True, verbose_name='NBI NICE')),
                ('cromoendoscopy', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Cromoendoscopy')),
                ('kudo', models.IntegerField(blank=True, choices=[(1, 'I'), (2, 'II'), (3, 'IIIS'), (4, 'IIIL'), (5, 'IV'), (6, 'V-I'), (7, 'V-N')], null=True, verbose_name='Kudo')),
                ('prepathologic_endoscopic_diagnostic_a', models.IntegerField(blank=True, choices=[(1, 'Adenoma'), (2, 'Serrated')], null=True, verbose_name='Prepathologic endoscopic diagnost 1')),
                ('prepathologic_endoscopic_diagnostic_b', models.IntegerField(blank=True, choices=[(1, 'NodisplasiaToSuperficial submucosal carcinoma'), (2, 'Deep submucosal carcinoma')], null=True, verbose_name='Prepathologic endoscopic diagnost 2')),
                ('correct_dx_adenoma_serrated', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Correct Dx Adenoma Serrated')),
                ('correct_dx_invasion', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Correct Dx Invasion')),
                ('histology', models.IntegerField(blank=True, choices=[(1, 'Adenoma'), (2, 'HGD-intraepitelial carcinoma in adenoma'), (3, 'Intramucosal carcinoma in adenoma'), (4, 'Superficial submucosal carcinoma in adenoma'), (5, 'Deep submucosal carcinoma in adenoma'), (6, 'Hyperplastic'), (7, 'Sesil Serrated polyp'), (8, 'Traditional Serrated Adenoma'), (9, 'Polyp Serrated Mixed or serrated polyp with dysplasia'), (10, 'Intraepitelial carcinoma Any serrated'), (11, 'Intramucosal carcinoma Any serrated'), (12, 'Superficial submucosa carc. Any serrated'), (13, 'Deep submucosa carc. Any serrated'), (14, 'Carinoid')], null=True, verbose_name='Histology')),
                ('histol_simplified', models.IntegerField(blank=True, choices=[(1, 'Adenoma'), (2, 'HGD-Imucosal'), (3, 'Invasive adenoma'), (4, 'Serrated'), (5, 'HGD-Imucosal serrated'), (6, 'Invasive serrated'), (7, 'Carcinoid')], null=True, verbose_name='Histology simplified')),
                ('time_of_procedure_in_mins', models.IntegerField(blank=True, null=True, verbose_name='Time of procedure (m)')),
                ('difficulty_of_emr', models.IntegerField(blank=True, choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Difficult')], null=True, verbose_name='Dificutly of EMR')),
                ('accesibility', models.IntegerField(blank=True, choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Difficult')], null=True, verbose_name='Accesibility')),
                ('resection', models.IntegerField(blank=True, choices=[(1, 'Piecemeal complete'), (2, 'Piecemeal incomplete'), (3, 'En bloc R0'), (4, 'En bloq incomplete')], null=True, verbose_name='Resection')),
                ('previous_biopsy', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Previous biopsy')),
                ('previous_attempt', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Previous attempt')),
                ('non_lifting_sign', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Non lifting sign')),
                ('technique', models.IntegerField(blank=True, choices=[(1, 'EMR'), (2, 'Hybrid-EMR')], null=True, verbose_name='Technique')),
                ('technique_two', models.IntegerField(blank=True, choices=[(1, 'One-step'), (2, 'Two-steps')], null=True, verbose_name=' Technique 2')),
                ('limit_marks', models.IntegerField(blank=True, choices=[(0, 'No marks'), (1, 'APC marks')], null=True, verbose_name='Limit marks')),
                ('injection', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Saline'), (2, 'Glicerin'), (3, 'Hyaluronic'), (4, 'Hidrox-propil-cellulose: VOLUVEN(r)'), (5, 'Gelafundin'), (6, 'Others')], null=True, verbose_name='Injection')),
                ('adrenaline', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Adrenaline')),
                ('endocut', models.IntegerField(blank=True, choices=[(1, 'Only cut current'), (2, 'Only coagulation current'), (3, 'Endocut/Blended')], null=True, verbose_name='Endocut/Blended')),
                ('electrosurgical_generator_model', models.CharField(blank=True, null=True, verbose_name='Electrosurgical generator model', max_length=100)),
                ('polyp_retrieval', models.IntegerField(blank=True, choices=[(1, 'Roth net'), (2, 'By aspiration'), (3, 'Both methods'), (4, 'By snare')], null=True, verbose_name='Polyp retrieval')),
                ('argon_PC', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes: incomplete resection'), (2, 'Yes: coagulation'), (3, 'Yes: per protocol')], null=True, verbose_name='Argon PC')),
                ('coagulation_forceps', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Coagulation forceps')),
                ('snare_tip_soft_coagulation', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Snare tip soft coagulation')),
                ('cs_cut_watts', models.IntegerField(blank=True, null=True, verbose_name='Cut (watts)')),
                ('cs_cut_mode', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], null=True, verbose_name='Endocut mode')),
                ('cs_coagulation_watts', models.IntegerField(blank=True, null=True, verbose_name='Coagulation (watts)')),
                ('cs_coagulation_mode', models.IntegerField(blank=True, choices=[(0, 'Soft'), (1, 'Force')], null=True, verbose_name='Coagulation mode')),
                ('clips_control_group', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Punctual coagulation')], null=True, verbose_name='Clips control group')),
                ('clips_tratment_group', models.IntegerField(blank=True, choices=[(1, 'Complete closure with complete mucosal apposition'), (2, 'Complete closure without complete mucosal apposition'), (3, 'Total failed closure'), (4, 'Partial failed closure'), (5, 'Closure not tried')], null=True, verbose_name='Clips treatment group')),
                ('clips_n_lote', models.IntegerField(blank=True, null=True, verbose_name='Lot number')),
                ('clips_exp_date', models.DateField(blank=True, null=True, verbose_name='Expiration date')),
                ('not_tired_closure_by', models.IntegerField(blank=True, choices=[(1, 'Big size'), (2, 'Difficult location'), (3, 'Both')], null=True, verbose_name='Closure not tried because of')),
                ('closure_technique', models.IntegerField(blank=True, choices=[(1, 'Simple clipping'), (2, 'Clip-Poly loop'), (3, 'Clip Silk loop')], null=True, verbose_name='Closure technique')),
                ('number_clips_needed', models.IntegerField(blank=True, null=True, verbose_name='Number of clips needed')),
                ('perforation', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes: endoscopic resolution'), (2, 'Yes: surgical resolution')], null=True, verbose_name='Perforation')),
                ('surgery_from_endoscopy', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Surgery from endoscopy')),
                ('surgery_by_complication', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes: bleeding'), (2, 'Yes: perforation')], null=True, verbose_name='Surgery by complication')),
                ('bleeding', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'During no clinical impact-autol'), (2, 'During exploration with clinical impact'), (3, '24h'), (4, '24-48h'), (5, '3-7 days'), (6, '>7 days')], null=True, verbose_name='Bleeding')),
                ('immediate_bleeding', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes: during exploration with clinical impact'), (2, 'Yes: during exploration without clinical impact')], null=True, verbose_name='Immediate bleeding')),
                ('delayed_bleeding', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Delayed bleeding')),
                ('bleeding_treatment', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Inyection'), (2, 'Clipping'), (3, 'ArgonPC'), (4, 'Coagulation forceps'), (5, '2 methods')], null=True, verbose_name='Bleeding treatment')),
                ('transfusion', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Transfusion')),
                ('pps', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Post polypectomy syndrome')),
                ('fever', models.IntegerField(blank=True, choices=[(0, 'No'), (1, '37-37.9'), (2, '38 or more')], null=True, verbose_name='Fever')),
                ('pain_requiring_medical_intervention', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Pain requiring medical intervantion')),
                ('hospital_stay_by_technique', models.IntegerField(blank=True, null=True, verbose_name='Hospital stay by technique')),
                ('hospital_stay_by_complication', models.IntegerField(blank=True, null=True, verbose_name='Hospital stay by complication')),
                ('follow_up_months', models.IntegerField(blank=True, null=True, verbose_name='Follow up months')),
                ('successful_treatment', models.IntegerField(blank=True, choices=[(0, 'No: surgical treatment'), (1, 'Yes: in 1 session (includes one or two steps'), (2, 'Yes, in 2 or more sessions (one session and treatment in controls')], null=True, verbose_name=' Successful treatment')),
                ('sedation', models.IntegerField(blank=True, choices=[(0, 'Without sedation'), (1, 'By gastroenterologist other than Propofol'), (2, 'By gastroenterologist based on Propofol'), (3, 'By anesthesiologist')], null=True, verbose_name='Sedation')),
                ('last_date_endoscopic_follow_up', models.DateField(blank=True, null=True, verbose_name='Last date endoscopic follow up')),
                ('recurrence_three_six_months_control', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes: positive biopsy: endoscopic treatment'), (2, 'Yes: visible recurrence: endoscopic treatment'), (3, 'Yes: surgical treatment needed')], null=True, verbose_name='Recurrence 3-6 months control')),
                ('recurrenec_one_year_control', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes: positive biopsy: endoscopic treatment'), (2, 'Yes: visible recurrence: endoscopic treatment'), (3, 'Yes: surgical treatment needed')], null=True, verbose_name='Recurrence 1 year control')),
                ('global_recurrence', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Global recurrence')),
                ('other_complications_comments', models.TextField(blank=True, null=True, verbose_name='Other complications comments', max_length=500)),
                ('other_comments', models.TextField(blank=True, null=True, verbose_name='Other comments', max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, verbose_name='ID', primary_key=True)),
                ('name', models.CharField(verbose_name='Name', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ObservationalCase',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, verbose_name='ID', primary_key=True)),
                ('group', models.IntegerField(blank=True, choices=[(0, 'Control group'), (1, 'Treatment group')], null=True, verbose_name='Group')),
                ('id_for_hospital', models.IntegerField(blank=True, null=True, verbose_name='Id for hospital')),
                ('id_for_doctor', models.IntegerField(blank=True, null=True, verbose_name='Id for doctor')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('age', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Age', null=True)),
                ('age_interval', models.IntegerField(blank=True, choices=[(1, '< 60'), (2, '60-74'), (3, '>= 75')], null=True, verbose_name='Age interval', max_length=2)),
                ('sex', models.IntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female')], null=True, verbose_name='Sex', max_length=1)),
                ('asa', models.IntegerField(blank=True, choices=[(1, 'I'), (2, 'II'), (3, 'III'), (4, 'IV')], null=True, verbose_name='ASA')),
                ('hypertension', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Hypertension')),
                ('hb', models.FloatField(blank=True, null=True, verbose_name='HB (g/dL)')),
                ('platelets', models.IntegerField(blank=True, null=True, verbose_name='Platelets (x10⁹/L)')),
                ('inr', models.FloatField(blank=True, null=True, verbose_name='INR')),
                ('pt', models.IntegerField(blank=True, null=True, verbose_name='PT (s)')),
                ('aspirin', models.IntegerField(blank=True, choices=[(0, 'No'), (1, '100mg cease'), (2, '300mg cease'), (3, '100mg during EMR'), (4, '300mg during EMR')], null=True, verbose_name='Aspirin')),
                ('anticoagulants', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Aspirin'), (2, 'Clopidogrel'), (3, 'Other antiagregant'), (4, 'Warfarin'), (5, 'NSAID'), (6, '2 NSAID including aspiring or not'), (7, 'Aspirin+clopidogrel'), (8, 'NACOs')], null=True, verbose_name='Anticoagulants')),
                ('heparinbridgetherapy', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Heparin Bridge Therapy')),
                ('nombre_p_activo_antiagreg_anticoag', models.IntegerField(blank=True, null=True, verbose_name='Active ingredients anticoagulant/antiagregant')),
                ('day_of_reintroduction_antiagregant', models.IntegerField(blank=True, null=True, verbose_name='Day of reintroduction anticoagulant/antiagregant')),
                ('paris_calif', models.IntegerField(blank=True, choices=[(1, '0Is'), (2, '0IIa'), (3, '0IIa+0Is'), (4, '0Is+0IIa'), (5, '0IIb'), (6, '0IIc'), (7, '0IIa+0IIc'), (8, '0IIb+0IIc'), (9, '0IIb+0IIa')], null=True, verbose_name='Paris Clasif.')),
                ('lst_yn', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='LST yn')),
                ('lst_morphology', models.IntegerField(blank=True, choices=[(1, 'Granular homogeneous'), (2, 'Focal nodular mixed type'), (3, 'Whole nodular mixed type'), (4, 'Flat elevated'), (5, 'Psudodepressed')], null=True, verbose_name='LST Morphology')),
                ('large_nodule_one_cm', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Large nodule 1cm')),
                ('demacrated_depressed_area', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Demacrated depressed area')),
                ('sclerous_wall_change', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Sclerous wall change')),
                ('fold_convergency', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Fold convergency')),
                ('chicken_skin_mucosa_around', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Chicken skin mucosa around')),
                ('maximum_size_mm', models.IntegerField(blank=True, null=True, verbose_name='Maximum size (mm)')),
                ('area_square_cm', models.IntegerField(blank=True, null=True, verbose_name='Area (cm2)')),
                ('location', models.IntegerField(blank=True, choices=[(1, 'Rectum'), (2, 'Left colon'), (3, 'Splenic flexure'), (4, 'Transverse'), (5, 'Hepatic'), (6, 'Ascendent'), (7, 'Cecum')], null=True, verbose_name='Location')),
                ('ileocecal_valve_involvement', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Ileocecal valve involvement')),
                ('high_definition', models.IntegerField(blank=True, choices=[(1, 'Conventional endoscope'), (2, 'High definition'), (3, 'Optic magnification')], null=True, verbose_name='High definition')),
                ('endoscopemodel', models.CharField(blank=True, null=True, verbose_name='Endoscope model', max_length=50)),
                ('nbi', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='NBI')),
                ('nbi_sano', models.IntegerField(blank=True, choices=[(1, 'I'), (2, 'II'), (3, 'IIIA'), (4, 'IIIB')], null=True, verbose_name='NBI sano')),
                ('nbi_nice', models.IntegerField(blank=True, choices=[(1, 'Type 1'), (2, 'Type 2'), (3, 'Type 3')], null=True, verbose_name='NBI NICE')),
                ('cromoendoscopy', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Cromoendoscopy')),
                ('kudo', models.IntegerField(blank=True, choices=[(1, 'I'), (2, 'II'), (3, 'IIIS'), (4, 'IIIL'), (5, 'IV'), (6, 'V-I'), (7, 'V-N')], null=True, verbose_name='Kudo')),
                ('prepathologic_endoscopic_diagnostic_a', models.IntegerField(blank=True, choices=[(1, 'Adenoma'), (2, 'Serrated')], null=True, verbose_name='Prepathologic endoscopic diagnost 1')),
                ('prepathologic_endoscopic_diagnostic_b', models.IntegerField(blank=True, choices=[(1, 'NodisplasiaToSuperficial submucosal carcinoma'), (2, 'Deep submucosal carcinoma')], null=True, verbose_name='Prepathologic endoscopic diagnost 2')),
                ('correct_dx_adenoma_serrated', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Correct Dx Adenoma Serrated')),
                ('correct_dx_invasion', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Correct Dx Invasion')),
                ('histology', models.IntegerField(blank=True, choices=[(1, 'Adenoma'), (2, 'HGD-intraepitelial carcinoma in adenoma'), (3, 'Intramucosal carcinoma in adenoma'), (4, 'Superficial submucosal carcinoma in adenoma'), (5, 'Deep submucosal carcinoma in adenoma'), (6, 'Hyperplastic'), (7, 'Sesil Serrated polyp'), (8, 'Traditional Serrated Adenoma'), (9, 'Polyp Serrated Mixed or serrated polyp with dysplasia'), (10, 'Intraepitelial carcinoma Any serrated'), (11, 'Intramucosal carcinoma Any serrated'), (12, 'Superficial submucosa carc. Any serrated'), (13, 'Deep submucosa carc. Any serrated'), (14, 'Carinoid')], null=True, verbose_name='Histology')),
                ('histol_simplified', models.IntegerField(blank=True, choices=[(1, 'Adenoma'), (2, 'HGD-Imucosal'), (3, 'Invasive adenoma'), (4, 'Serrated'), (5, 'HGD-Imucosal serrated'), (6, 'Invasive serrated'), (7, 'Carcinoid')], null=True, verbose_name='Histology simplified')),
                ('time_of_procedure_in_mins', models.IntegerField(blank=True, null=True, verbose_name='Time of procedure (m)')),
                ('difficulty_of_emr', models.IntegerField(blank=True, choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Difficult')], null=True, verbose_name='Dificutly of EMR')),
                ('accesibility', models.IntegerField(blank=True, choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Difficult')], null=True, verbose_name='Accesibility')),
                ('resection', models.IntegerField(blank=True, choices=[(1, 'Piecemeal complete'), (2, 'Piecemeal incomplete'), (3, 'En bloc R0'), (4, 'En bloq incomplete')], null=True, verbose_name='Resection')),
                ('previous_biopsy', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Previous biopsy')),
                ('previous_attempt', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Previous attempt')),
                ('non_lifting_sign', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Non lifting sign')),
                ('technique', models.IntegerField(blank=True, choices=[(1, 'EMR'), (2, 'Hybrid-EMR')], null=True, verbose_name='Technique')),
                ('technique_two', models.IntegerField(blank=True, choices=[(1, 'One-step'), (2, 'Two-steps')], null=True, verbose_name=' Technique 2')),
                ('limit_marks', models.IntegerField(blank=True, choices=[(0, 'No marks'), (1, 'APC marks')], null=True, verbose_name='Limit marks')),
                ('injection', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Saline'), (2, 'Glicerin'), (3, 'Hyaluronic'), (4, 'Hidrox-propil-cellulose: VOLUVEN(r)'), (5, 'Gelafundin'), (6, 'Others')], null=True, verbose_name='Injection')),
                ('adrenaline', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Adrenaline')),
                ('endocut', models.IntegerField(blank=True, choices=[(1, 'Only cut current'), (2, 'Only coagulation current'), (3, 'Endocut/Blended')], null=True, verbose_name='Endocut/Blended')),
                ('electrosurgical_generator_model', models.CharField(blank=True, null=True, verbose_name='Electrosurgical generator model', max_length=100)),
                ('polyp_retrieval', models.IntegerField(blank=True, choices=[(1, 'Roth net'), (2, 'By aspiration'), (3, 'Both methods'), (4, 'By snare')], null=True, verbose_name='Polyp retrieval')),
                ('argon_PC', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes: incomplete resection'), (2, 'Yes: coagulation'), (3, 'Yes: per protocol')], null=True, verbose_name='Argon PC')),
                ('coagulation_forceps', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Coagulation forceps')),
                ('snare_tip_soft_coagulation', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Snare tip soft coagulation')),
                ('cs_cut_watts', models.IntegerField(blank=True, null=True, verbose_name='Cut (watts)')),
                ('cs_cut_mode', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], null=True, verbose_name='Endocut mode')),
                ('cs_coagulation_watts', models.IntegerField(blank=True, null=True, verbose_name='Coagulation (watts)')),
                ('cs_coagulation_mode', models.IntegerField(blank=True, choices=[(0, 'Soft'), (1, 'Force')], null=True, verbose_name='Coagulation mode')),
                ('clips_control_group', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Punctual coagulation')], null=True, verbose_name='Clips control group')),
                ('clips_tratment_group', models.IntegerField(blank=True, choices=[(1, 'Complete closure with complete mucosal apposition'), (2, 'Complete closure without complete mucosal apposition'), (3, 'Total failed closure'), (4, 'Partial failed closure'), (5, 'Closure not tried')], null=True, verbose_name='Clips treatment group')),
                ('clips_n_lote', models.IntegerField(blank=True, null=True, verbose_name='Lot number')),
                ('clips_exp_date', models.DateField(blank=True, null=True, verbose_name='Expiration date')),
                ('not_tired_closure_by', models.IntegerField(blank=True, choices=[(1, 'Big size'), (2, 'Difficult location'), (3, 'Both')], null=True, verbose_name='Closure not tried because of')),
                ('closure_technique', models.IntegerField(blank=True, choices=[(1, 'Simple clipping'), (2, 'Clip-Poly loop'), (3, 'Clip Silk loop')], null=True, verbose_name='Closure technique')),
                ('number_clips_needed', models.IntegerField(blank=True, null=True, verbose_name='Number of clips needed')),
                ('perforation', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes: endoscopic resolution'), (2, 'Yes: surgical resolution')], null=True, verbose_name='Perforation')),
                ('surgery_from_endoscopy', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Surgery from endoscopy')),
                ('surgery_by_complication', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes: bleeding'), (2, 'Yes: perforation')], null=True, verbose_name='Surgery by complication')),
                ('bleeding', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'During no clinical impact-autol'), (2, 'During exploration with clinical impact'), (3, '24h'), (4, '24-48h'), (5, '3-7 days'), (6, '>7 days')], null=True, verbose_name='Bleeding')),
                ('immediate_bleeding', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes: during exploration with clinical impact'), (2, 'Yes: during exploration without clinical impact')], null=True, verbose_name='Immediate bleeding')),
                ('delayed_bleeding', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Delayed bleeding')),
                ('bleeding_treatment', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Inyection'), (2, 'Clipping'), (3, 'ArgonPC'), (4, 'Coagulation forceps'), (5, '2 methods')], null=True, verbose_name='Bleeding treatment')),
                ('transfusion', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Transfusion')),
                ('pps', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Post polypectomy syndrome')),
                ('fever', models.IntegerField(blank=True, choices=[(0, 'No'), (1, '37-37.9'), (2, '38 or more')], null=True, verbose_name='Fever')),
                ('pain_requiring_medical_intervention', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Pain requiring medical intervantion')),
                ('hospital_stay_by_technique', models.IntegerField(blank=True, null=True, verbose_name='Hospital stay by technique')),
                ('hospital_stay_by_complication', models.IntegerField(blank=True, null=True, verbose_name='Hospital stay by complication')),
                ('follow_up_months', models.IntegerField(blank=True, null=True, verbose_name='Follow up months')),
                ('successful_treatment', models.IntegerField(blank=True, choices=[(0, 'No: surgical treatment'), (1, 'Yes: in 1 session (includes one or two steps'), (2, 'Yes, in 2 or more sessions (one session and treatment in controls')], null=True, verbose_name=' Successful treatment')),
                ('sedation', models.IntegerField(blank=True, choices=[(0, 'Without sedation'), (1, 'By gastroenterologist other than Propofol'), (2, 'By gastroenterologist based on Propofol'), (3, 'By anesthesiologist')], null=True, verbose_name='Sedation')),
                ('last_date_endoscopic_follow_up', models.DateField(blank=True, null=True, verbose_name='Last date endoscopic follow up')),
                ('recurrence_three_six_months_control', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes: positive biopsy: endoscopic treatment'), (2, 'Yes: visible recurrence: endoscopic treatment'), (3, 'Yes: surgical treatment needed')], null=True, verbose_name='Recurrence 3-6 months control')),
                ('recurrenec_one_year_control', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes: positive biopsy: endoscopic treatment'), (2, 'Yes: visible recurrence: endoscopic treatment'), (3, 'Yes: surgical treatment needed')], null=True, verbose_name='Recurrence 1 year control')),
                ('global_recurrence', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Global recurrence')),
                ('other_complications_comments', models.TextField(blank=True, null=True, verbose_name='Other complications comments', max_length=500)),
                ('other_comments', models.TextField(blank=True, null=True, verbose_name='Other comments', max_length=500)),
                ('colonoscopy_indication', models.IntegerField(blank=True, choices=[(1, 'Anemia/iron deficiency'), (2, 'CRC suspected'), (3, 'CRC screening program'), (4, 'Postpolypectomy surveillance'), (5, 'Relatives with CRC or polyposis'), (6, 'Polyposis'), (7, 'Other')], null=True, verbose_name='Colonoscopy indication')),
                ('country', models.IntegerField(blank=True, choices=[(1, 'Spain'), (2, 'Japan'), (3, 'UK'), (4, 'USA'), (5, 'China')], null=True, verbose_name='Country')),
                ('depth', models.IntegerField(blank=True, choices=[(1, 'Mucosa'), (2, 'SM1'), (3, 'SM2'), (4, 'SM3'), (5, 'MP or deeper')], null=True, verbose_name='Depth')),
                ('depth_sm_invasion', models.FloatField(blank=True, null=True, verbose_name='Depth (Sm invasion: µ)')),
                ('lymphatic_invasion', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Lymphatic invasion')),
                ('vascular_invasion', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Vascular invasion')),
                ('perineural_invasion', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Perineural invasion')),
                ('budding', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'High grade')], null=True, verbose_name='Budding')),
                ('degree_differentiation', models.IntegerField(blank=True, choices=[(1, 'Well'), (2, 'Moderate'), (3, 'Poorly')], null=True, verbose_name='Degree differentiation')),
                ('histological_variants', models.IntegerField(blank=True, choices=[(1, 'Adenocarcinoma'), (2, 'Mucinous'), (3, 'Medullary'), (4, 'Signet ring')], null=True, verbose_name='Histological variants')),
                ('free_vertical_margins', models.IntegerField(blank=True, choices=[(1, 'Nonassessable'), (2, 'Free'), (3, 'Affected')], null=True, verbose_name='Free vertical margins (>1mm)')),
                ('free_horizontal_margins', models.IntegerField(blank=True, choices=[(1, 'Nonassessable'), (2, 'Free'), (3, 'Affected')], null=True, verbose_name='Free horizontal margin (>1mm)')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ObsinternationalCase',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, verbose_name='ID', primary_key=True)),
                ('group', models.IntegerField(blank=True, choices=[(0, 'Control group'), (1, 'Treatment group')], null=True, verbose_name='Group')),
                ('id_for_hospital', models.IntegerField(blank=True, null=True, verbose_name='Id for hospital')),
                ('id_for_doctor', models.IntegerField(blank=True, null=True, verbose_name='Id for doctor')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('age', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Age', null=True)),
                ('age_interval', models.IntegerField(blank=True, choices=[(1, '< 60'), (2, '60-74'), (3, '>= 75')], null=True, verbose_name='Age interval', max_length=2)),
                ('sex', models.IntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female')], null=True, verbose_name='Sex', max_length=1)),
                ('asa', models.IntegerField(blank=True, choices=[(1, 'I'), (2, 'II'), (3, 'III'), (4, 'IV')], null=True, verbose_name='ASA')),
                ('hypertension', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Hypertension')),
                ('hb', models.FloatField(blank=True, null=True, verbose_name='HB (g/dL)')),
                ('platelets', models.IntegerField(blank=True, null=True, verbose_name='Platelets (x10⁹/L)')),
                ('inr', models.FloatField(blank=True, null=True, verbose_name='INR')),
                ('pt', models.IntegerField(blank=True, null=True, verbose_name='PT (s)')),
                ('aspirin', models.IntegerField(blank=True, choices=[(0, 'No'), (1, '100mg cease'), (2, '300mg cease'), (3, '100mg during EMR'), (4, '300mg during EMR')], null=True, verbose_name='Aspirin')),
                ('anticoagulants', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Aspirin'), (2, 'Clopidogrel'), (3, 'Other antiagregant'), (4, 'Warfarin'), (5, 'NSAID'), (6, '2 NSAID including aspiring or not'), (7, 'Aspirin+clopidogrel'), (8, 'NACOs')], null=True, verbose_name='Anticoagulants')),
                ('heparinbridgetherapy', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Heparin Bridge Therapy')),
                ('nombre_p_activo_antiagreg_anticoag', models.IntegerField(blank=True, null=True, verbose_name='Active ingredients anticoagulant/antiagregant')),
                ('day_of_reintroduction_antiagregant', models.IntegerField(blank=True, null=True, verbose_name='Day of reintroduction anticoagulant/antiagregant')),
                ('paris_calif', models.IntegerField(blank=True, choices=[(1, '0Is'), (2, '0IIa'), (3, '0IIa+0Is'), (4, '0Is+0IIa'), (5, '0IIb'), (6, '0IIc'), (7, '0IIa+0IIc'), (8, '0IIb+0IIc'), (9, '0IIb+0IIa')], null=True, verbose_name='Paris Clasif.')),
                ('lst_yn', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='LST yn')),
                ('lst_morphology', models.IntegerField(blank=True, choices=[(1, 'Granular homogeneous'), (2, 'Focal nodular mixed type'), (3, 'Whole nodular mixed type'), (4, 'Flat elevated'), (5, 'Psudodepressed')], null=True, verbose_name='LST Morphology')),
                ('large_nodule_one_cm', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Large nodule 1cm')),
                ('demacrated_depressed_area', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Demacrated depressed area')),
                ('sclerous_wall_change', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Sclerous wall change')),
                ('fold_convergency', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Fold convergency')),
                ('chicken_skin_mucosa_around', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Chicken skin mucosa around')),
                ('maximum_size_mm', models.IntegerField(blank=True, null=True, verbose_name='Maximum size (mm)')),
                ('area_square_cm', models.IntegerField(blank=True, null=True, verbose_name='Area (cm2)')),
                ('location', models.IntegerField(blank=True, choices=[(1, 'Rectum'), (2, 'Left colon'), (3, 'Splenic flexure'), (4, 'Transverse'), (5, 'Hepatic'), (6, 'Ascendent'), (7, 'Cecum')], null=True, verbose_name='Location')),
                ('ileocecal_valve_involvement', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Ileocecal valve involvement')),
                ('high_definition', models.IntegerField(blank=True, choices=[(1, 'Conventional endoscope'), (2, 'High definition'), (3, 'Optic magnification')], null=True, verbose_name='High definition')),
                ('endoscopemodel', models.CharField(blank=True, null=True, verbose_name='Endoscope model', max_length=50)),
                ('nbi', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='NBI')),
                ('nbi_sano', models.IntegerField(blank=True, choices=[(1, 'I'), (2, 'II'), (3, 'IIIA'), (4, 'IIIB')], null=True, verbose_name='NBI sano')),
                ('nbi_nice', models.IntegerField(blank=True, choices=[(1, 'Type 1'), (2, 'Type 2'), (3, 'Type 3')], null=True, verbose_name='NBI NICE')),
                ('cromoendoscopy', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Cromoendoscopy')),
                ('kudo', models.IntegerField(blank=True, choices=[(1, 'I'), (2, 'II'), (3, 'IIIS'), (4, 'IIIL'), (5, 'IV'), (6, 'V-I'), (7, 'V-N')], null=True, verbose_name='Kudo')),
                ('prepathologic_endoscopic_diagnostic_a', models.IntegerField(blank=True, choices=[(1, 'Adenoma'), (2, 'Serrated')], null=True, verbose_name='Prepathologic endoscopic diagnost 1')),
                ('prepathologic_endoscopic_diagnostic_b', models.IntegerField(blank=True, choices=[(1, 'NodisplasiaToSuperficial submucosal carcinoma'), (2, 'Deep submucosal carcinoma')], null=True, verbose_name='Prepathologic endoscopic diagnost 2')),
                ('correct_dx_adenoma_serrated', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Correct Dx Adenoma Serrated')),
                ('correct_dx_invasion', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Correct Dx Invasion')),
                ('histology', models.IntegerField(blank=True, choices=[(1, 'Adenoma'), (2, 'HGD-intraepitelial carcinoma in adenoma'), (3, 'Intramucosal carcinoma in adenoma'), (4, 'Superficial submucosal carcinoma in adenoma'), (5, 'Deep submucosal carcinoma in adenoma'), (6, 'Hyperplastic'), (7, 'Sesil Serrated polyp'), (8, 'Traditional Serrated Adenoma'), (9, 'Polyp Serrated Mixed or serrated polyp with dysplasia'), (10, 'Intraepitelial carcinoma Any serrated'), (11, 'Intramucosal carcinoma Any serrated'), (12, 'Superficial submucosa carc. Any serrated'), (13, 'Deep submucosa carc. Any serrated'), (14, 'Carinoid')], null=True, verbose_name='Histology')),
                ('histol_simplified', models.IntegerField(blank=True, choices=[(1, 'Adenoma'), (2, 'HGD-Imucosal'), (3, 'Invasive adenoma'), (4, 'Serrated'), (5, 'HGD-Imucosal serrated'), (6, 'Invasive serrated'), (7, 'Carcinoid')], null=True, verbose_name='Histology simplified')),
                ('time_of_procedure_in_mins', models.IntegerField(blank=True, null=True, verbose_name='Time of procedure (m)')),
                ('difficulty_of_emr', models.IntegerField(blank=True, choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Difficult')], null=True, verbose_name='Dificutly of EMR')),
                ('accesibility', models.IntegerField(blank=True, choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Difficult')], null=True, verbose_name='Accesibility')),
                ('resection', models.IntegerField(blank=True, choices=[(1, 'Piecemeal complete'), (2, 'Piecemeal incomplete'), (3, 'En bloc R0'), (4, 'En bloq incomplete')], null=True, verbose_name='Resection')),
                ('previous_biopsy', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Previous biopsy')),
                ('previous_attempt', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Previous attempt')),
                ('non_lifting_sign', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Non lifting sign')),
                ('technique', models.IntegerField(blank=True, choices=[(1, 'EMR'), (2, 'Hybrid-EMR')], null=True, verbose_name='Technique')),
                ('technique_two', models.IntegerField(blank=True, choices=[(1, 'One-step'), (2, 'Two-steps')], null=True, verbose_name=' Technique 2')),
                ('limit_marks', models.IntegerField(blank=True, choices=[(0, 'No marks'), (1, 'APC marks')], null=True, verbose_name='Limit marks')),
                ('injection', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Saline'), (2, 'Glicerin'), (3, 'Hyaluronic'), (4, 'Hidrox-propil-cellulose: VOLUVEN(r)'), (5, 'Gelafundin'), (6, 'Others')], null=True, verbose_name='Injection')),
                ('adrenaline', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Adrenaline')),
                ('endocut', models.IntegerField(blank=True, choices=[(1, 'Only cut current'), (2, 'Only coagulation current'), (3, 'Endocut/Blended')], null=True, verbose_name='Endocut/Blended')),
                ('electrosurgical_generator_model', models.CharField(blank=True, null=True, verbose_name='Electrosurgical generator model', max_length=100)),
                ('polyp_retrieval', models.IntegerField(blank=True, choices=[(1, 'Roth net'), (2, 'By aspiration'), (3, 'Both methods'), (4, 'By snare')], null=True, verbose_name='Polyp retrieval')),
                ('argon_PC', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes: incomplete resection'), (2, 'Yes: coagulation'), (3, 'Yes: per protocol')], null=True, verbose_name='Argon PC')),
                ('coagulation_forceps', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Coagulation forceps')),
                ('snare_tip_soft_coagulation', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Snare tip soft coagulation')),
                ('cs_cut_watts', models.IntegerField(blank=True, null=True, verbose_name='Cut (watts)')),
                ('cs_cut_mode', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], null=True, verbose_name='Endocut mode')),
                ('cs_coagulation_watts', models.IntegerField(blank=True, null=True, verbose_name='Coagulation (watts)')),
                ('cs_coagulation_mode', models.IntegerField(blank=True, choices=[(0, 'Soft'), (1, 'Force')], null=True, verbose_name='Coagulation mode')),
                ('clips_control_group', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Punctual coagulation')], null=True, verbose_name='Clips control group')),
                ('clips_tratment_group', models.IntegerField(blank=True, choices=[(1, 'Complete closure with complete mucosal apposition'), (2, 'Complete closure without complete mucosal apposition'), (3, 'Total failed closure'), (4, 'Partial failed closure'), (5, 'Closure not tried')], null=True, verbose_name='Clips treatment group')),
                ('clips_n_lote', models.IntegerField(blank=True, null=True, verbose_name='Lot number')),
                ('clips_exp_date', models.DateField(blank=True, null=True, verbose_name='Expiration date')),
                ('not_tired_closure_by', models.IntegerField(blank=True, choices=[(1, 'Big size'), (2, 'Difficult location'), (3, 'Both')], null=True, verbose_name='Closure not tried because of')),
                ('closure_technique', models.IntegerField(blank=True, choices=[(1, 'Simple clipping'), (2, 'Clip-Poly loop'), (3, 'Clip Silk loop')], null=True, verbose_name='Closure technique')),
                ('number_clips_needed', models.IntegerField(blank=True, null=True, verbose_name='Number of clips needed')),
                ('perforation', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes: endoscopic resolution'), (2, 'Yes: surgical resolution')], null=True, verbose_name='Perforation')),
                ('surgery_from_endoscopy', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Surgery from endoscopy')),
                ('surgery_by_complication', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes: bleeding'), (2, 'Yes: perforation')], null=True, verbose_name='Surgery by complication')),
                ('bleeding', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'During no clinical impact-autol'), (2, 'During exploration with clinical impact'), (3, '24h'), (4, '24-48h'), (5, '3-7 days'), (6, '>7 days')], null=True, verbose_name='Bleeding')),
                ('immediate_bleeding', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes: during exploration with clinical impact'), (2, 'Yes: during exploration without clinical impact')], null=True, verbose_name='Immediate bleeding')),
                ('delayed_bleeding', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Delayed bleeding')),
                ('bleeding_treatment', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Inyection'), (2, 'Clipping'), (3, 'ArgonPC'), (4, 'Coagulation forceps'), (5, '2 methods')], null=True, verbose_name='Bleeding treatment')),
                ('transfusion', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Transfusion')),
                ('pps', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Post polypectomy syndrome')),
                ('fever', models.IntegerField(blank=True, choices=[(0, 'No'), (1, '37-37.9'), (2, '38 or more')], null=True, verbose_name='Fever')),
                ('pain_requiring_medical_intervention', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Pain requiring medical intervantion')),
                ('hospital_stay_by_technique', models.IntegerField(blank=True, null=True, verbose_name='Hospital stay by technique')),
                ('hospital_stay_by_complication', models.IntegerField(blank=True, null=True, verbose_name='Hospital stay by complication')),
                ('follow_up_months', models.IntegerField(blank=True, null=True, verbose_name='Follow up months')),
                ('successful_treatment', models.IntegerField(blank=True, choices=[(0, 'No: surgical treatment'), (1, 'Yes: in 1 session (includes one or two steps'), (2, 'Yes, in 2 or more sessions (one session and treatment in controls')], null=True, verbose_name=' Successful treatment')),
                ('sedation', models.IntegerField(blank=True, choices=[(0, 'Without sedation'), (1, 'By gastroenterologist other than Propofol'), (2, 'By gastroenterologist based on Propofol'), (3, 'By anesthesiologist')], null=True, verbose_name='Sedation')),
                ('last_date_endoscopic_follow_up', models.DateField(blank=True, null=True, verbose_name='Last date endoscopic follow up')),
                ('recurrence_three_six_months_control', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes: positive biopsy: endoscopic treatment'), (2, 'Yes: visible recurrence: endoscopic treatment'), (3, 'Yes: surgical treatment needed')], null=True, verbose_name='Recurrence 3-6 months control')),
                ('recurrenec_one_year_control', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes: positive biopsy: endoscopic treatment'), (2, 'Yes: visible recurrence: endoscopic treatment'), (3, 'Yes: surgical treatment needed')], null=True, verbose_name='Recurrence 1 year control')),
                ('global_recurrence', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Global recurrence')),
                ('other_complications_comments', models.TextField(blank=True, null=True, verbose_name='Other complications comments', max_length=500)),
                ('other_comments', models.TextField(blank=True, null=True, verbose_name='Other comments', max_length=500)),
                ('colonoscopy_indication', models.IntegerField(blank=True, choices=[(1, 'Anemia/iron deficiency'), (2, 'CRC suspected'), (3, 'CRC screening program'), (4, 'Postpolypectomy surveillance'), (5, 'Relatives with CRC or polyposis'), (6, 'Polyposis'), (7, 'Other')], null=True, verbose_name='Colonoscopy indication')),
                ('country', models.IntegerField(blank=True, choices=[(1, 'Spain'), (2, 'Japan'), (3, 'UK'), (4, 'USA'), (5, 'China')], null=True, verbose_name='Country')),
                ('depth', models.IntegerField(blank=True, choices=[(1, 'Mucosa'), (2, 'SM1'), (3, 'SM2'), (4, 'SM3'), (5, 'MP or deeper')], null=True, verbose_name='Depth')),
                ('depth_sm_invasion', models.FloatField(blank=True, null=True, verbose_name='Depth (Sm invasion: µ)')),
                ('lymphatic_invasion', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Lymphatic invasion')),
                ('vascular_invasion', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Vascular invasion')),
                ('perineural_invasion', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Perineural invasion')),
                ('budding', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'High grade')], null=True, verbose_name='Budding')),
                ('degree_differentiation', models.IntegerField(blank=True, choices=[(1, 'Well'), (2, 'Moderate'), (3, 'Poorly')], null=True, verbose_name='Degree differentiation')),
                ('histological_variants', models.IntegerField(blank=True, choices=[(1, 'Adenocarcinoma'), (2, 'Mucinous'), (3, 'Medullary'), (4, 'Signet ring')], null=True, verbose_name='Histological variants')),
                ('free_vertical_margins', models.IntegerField(blank=True, choices=[(1, 'Nonassessable'), (2, 'Free'), (3, 'Affected')], null=True, verbose_name='Free vertical margins (>1mm)')),
                ('free_horizontal_margins', models.IntegerField(blank=True, choices=[(1, 'Nonassessable'), (2, 'Free'), (3, 'Affected')], null=True, verbose_name='Free horizontal margin (>1mm)')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, verbose_name='ID', primary_key=True)),
                ('name', models.CharField(max_length=64)),
                ('study_type', models.CharField(choices=[('clips', 'Clips Study'), ('cancer', 'Cancer Study'), ('observational', 'Observational Study'), ('obsinternational', 'International Observational Study')], verbose_name='Study type', max_length=64)),
            ],
            options={
                'verbose_name_plural': 'Studies',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, verbose_name='ID', primary_key=True)),
                ('hospital', models.ForeignKey(null=True, to='studies_app.Hospital')),
                ('studies', models.ManyToManyField(to='studies_app.Study')),
                ('user', models.OneToOneField(to=settings.AUTH_USER_MODEL, related_name='clips_userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='obsinternationalcase',
            name='doctor',
            field=models.ForeignKey(null=True, verbose_name='Doctor', blank=True, to='studies_app.UserProfile'),
        ),
        migrations.AddField(
            model_name='obsinternationalcase',
            name='study',
            field=models.ForeignKey(to='studies_app.Study', verbose_name='Study', related_name='cases_obsinternationalcase'),
        ),
        migrations.AddField(
            model_name='observationalcase',
            name='doctor',
            field=models.ForeignKey(null=True, verbose_name='Doctor', blank=True, to='studies_app.UserProfile'),
        ),
        migrations.AddField(
            model_name='observationalcase',
            name='study',
            field=models.ForeignKey(to='studies_app.Study', verbose_name='Study', related_name='cases_observationalcase'),
        ),
        migrations.AddField(
            model_name='clipscase',
            name='doctor',
            field=models.ForeignKey(null=True, verbose_name='Doctor', blank=True, to='studies_app.UserProfile'),
        ),
        migrations.AddField(
            model_name='clipscase',
            name='study',
            field=models.ForeignKey(to='studies_app.Study', verbose_name='Study', related_name='cases_clipscase'),
        ),
        migrations.AddField(
            model_name='cancercase',
            name='doctor',
            field=models.ForeignKey(null=True, verbose_name='Doctor', blank=True, to='studies_app.UserProfile'),
        ),
        migrations.AddField(
            model_name='cancercase',
            name='study',
            field=models.ForeignKey(to='studies_app.Study', verbose_name='Study', related_name='cases_cancercase'),
        ),
    ]
