# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies_app', '0007_auto_20161205_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='accesibility',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='adrenaline',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='age',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='age_interval',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='anticoagulants',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='area_square_cm',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='argon_PC',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='asa',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='aspirin',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='bleeding',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='bleeding_treatment',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='budding',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='chicken_skin_mucosa_around',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='clips_control_group',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='clips_exp_date',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='clips_n_lote',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='clips_tratment_group',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='closure_technique',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='coagulation_forceps',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='colonoscopy_indication',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='correct_dx_adenoma_serrated',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='correct_dx_invasion',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='country',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='cromoendoscopy',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='cs_coagulation_mode',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='cs_coagulation_watts',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='cs_cut_mode',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='cs_cut_watts',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='date',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='day_of_reintroduction_antiagregant',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='degree_differentiation',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='delayed_bleeding',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='demacrated_depressed_area',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='depth',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='depth_sm_invasion',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='difficulty_of_emr',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='electrosurgical_generator_model',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='endocut',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='endoscopemodel',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='fever',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='fold_convergency',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='follow_up_months',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='free_horizontal_margins',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='free_vertical_margins',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='global_recurrence',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='group',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='hb',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='heparinbridgetherapy',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='high_definition',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='histol_simplified',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='histological_variants',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='histology',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='hospital_stay_by_complication',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='hospital_stay_by_technique',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='hypertension',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='id',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='id_for_doctor',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='id_for_hospital',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='ileocecal_valve_involvement',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='immediate_bleeding',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='injection',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='inr',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='kudo',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='large_nodule_one_cm',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='last_date_endoscopic_follow_up',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='limit_marks',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='location',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='lst_morphology',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='lst_yn',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='lymphatic_invasion',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='maximum_size_mm',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='nbi',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='nbi_nice',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='nbi_sano',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='nombre_p_activo_antiagreg_anticoag',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='non_lifting_sign',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='not_tired_closure_by',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='number_clips_needed',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='other_comments',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='other_complications_comments',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='pain_requiring_medical_intervention',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='paris_calif',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='perforation',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='perineural_invasion',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='platelets',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='polyp_retrieval',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='pps',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='prepathologic_endoscopic_diagnostic_a',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='prepathologic_endoscopic_diagnostic_b',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='previous_attempt',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='previous_biopsy',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='pt',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='recurrence_three_six_months_control',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='recurrenec_one_year_control',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='resection',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='sclerous_wall_change',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='sedation',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='snare_tip_soft_coagulation',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='study',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='successful_treatment',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='surgery_by_complication',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='surgery_from_endoscopy',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='technique',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='technique_two',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='time_of_procedure_in_mins',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='transfusion',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='vascular_invasion',
        ),
        migrations.AddField(
            model_name='obsinternationalcase',
            name='observationalcase_ptr',
            field=models.OneToOneField(to='studies_app.ObservationalCase', serialize=False, auto_created=True, primary_key=True, parent_link=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='observationalcase',
            name='case_number',
            field=models.IntegerField(verbose_name='Case number', blank=True, null=True),
        ),
    ]
