# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies_app', '0009_auto_20161205_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='accesibility',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='adrenaline',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='age',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='age_interval',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='anticoagulants',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='area_square_cm',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='argon_PC',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='asa',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='aspirin',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='bleeding',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='bleeding_treatment',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='boston',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='boston_left',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='boston_right',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='boston_transverse',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='budding',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='case_number',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='chicken_skin_mucosa_around',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='chromoendoscopy',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='clipping',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='closure_technique',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='coagulation_forceps',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='colonoscopy_indication',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='correct_dx_adenoma_serrated',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='correct_dx_invasion',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='country',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='date',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='day_of_reintroduction_antiagregant',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='degree_differentiation',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='delayed_bleeding',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='demarcated_depressed_area',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='depth',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='depth_sm_invasion',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='difficult_locations',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='difficulty_of_emr',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='dye_submucosal_injection',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='electrosurgical_generator_model',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='endocut',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='endoscopemodel',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='endoscopic_technique',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='endoscopist',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='fever',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='fold_convergency',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='follow_up_months',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='free_horizontal_margins',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='free_vertical_margins',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='global_recurrence',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='heparinbridgetherapy',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='high_definition',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='histological_variants',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='histology',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='hospital_stay_by_complication',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='hospital_stay_by_technique',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='hypertension',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='id_number',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='immediate_bleeding',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='injection',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='kudo',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='large_nodule_one_cm',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='last_date_endoscopic_follow_up',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='laxative',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='laxative_schedule',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='limit_marks',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='location',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='lst_morphology',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='lst_yn',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='lymphatic_invasion',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='maximum_size_mm',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='nbi',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='nbi_nice',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='nbi_sano',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='nombre_p_activo_antiagreg_anticoag',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='non_lifting_sign',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='number_clips_needed',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='number_of_sessions',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='other_coagulopathies',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='other_comments',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='other_complications_comments',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='pain_requiring_medical_intervention',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='paris_calif',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='perforation',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='perineural_invasion',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='platelets',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='pps',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='prepathologic_endoscopic_diagnostic_a',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='prepathologic_endoscopic_diagnostic_b',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='previous_attempt',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='previous_biopsy',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='recurrence_three_six_months_control',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='recurrenec_one_year_control',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='resection',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='sclerous_wall_change',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='sedation',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='snare_tip_soft_coagulation',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='successful_treatment',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='surgery',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='time_of_procedure_in_mins',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='transfusion',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='treatment_of_residual_polyp',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='vascular_invasion',
        ),
        migrations.RemoveField(
            model_name='obsinternationalcase',
            name='visible_scar',
        ),
    ]
