# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('studies_app', '0015_auto_20161026_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservationalCase',
            fields=[
                ('id', models.AutoField(verbose_name='ID', auto_created=True, primary_key=True, serialize=False)),
                ('group', models.IntegerField(verbose_name='Clips', blank=True, null=True, choices=[(0, 'Control group'), (1, 'Treatment group')])),
                ('id_for_hospital', models.IntegerField(verbose_name='Id for hospital', blank=True, null=True)),
                ('id_for_doctor', models.IntegerField(verbose_name='Id for doctor', blank=True, null=True)),
                ('date', models.DateField(verbose_name='Date', blank=True, null=True)),
                ('age', models.IntegerField(verbose_name='Age', blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('age_interval', models.IntegerField(verbose_name='Age interval', blank=True, null=True, max_length=2, choices=[(1, '< 60'), (2, '60-74'), (3, '>= 75')])),
                ('sex', models.IntegerField(verbose_name='Sex', blank=True, null=True, max_length=1, choices=[(1, 'Male'), (2, 'Female')])),
                ('asa', models.IntegerField(verbose_name='ASA', blank=True, null=True, choices=[(1, 'I'), (2, 'II'), (3, 'III'), (4, 'IV')])),
                ('hypertension', models.IntegerField(verbose_name='Hypertension', blank=True, null=True, choices=[(0, 'No'), (1, 'Yes')])),
                ('hb', models.FloatField(verbose_name='HB (g/dL)', blank=True, null=True)),
                ('platelets', models.IntegerField(verbose_name='Platelets (x10⁹/L)', blank=True, null=True)),
                ('inr', models.FloatField(verbose_name='INR', blank=True, null=True)),
                ('pt', models.IntegerField(verbose_name='PT (s)', blank=True, null=True)),
                ('aspirin', models.IntegerField(verbose_name='Aspirin', blank=True, null=True, choices=[(0, 'No'), (1, '100mg cease'), (2, '300mg cease'), (3, '100mg during EMR'), (4, '300mg during EMR')])),
                ('anticoagulants', models.IntegerField(verbose_name='Anticoagulants', blank=True, null=True, choices=[(0, 'No'), (1, 'Aspirin'), (2, 'Clopidogrel'), (3, 'Other antiagregant'), (4, 'Warfarin'), (5, 'NSAID'), (6, '2 NSAID including aspiring or not'), (7, 'Aspirin+clopidogrel'), (8, 'NACOs')])),
                ('heparinbridgetherapy', models.IntegerField(verbose_name='Heparin Bridge Therapy', blank=True, null=True, choices=[(0, 'No'), (1, 'Yes')])),
                ('nombre_p_activo_antiagreg_anticoag', models.IntegerField(verbose_name='Active ingredients anticoagulant/antiagregant', blank=True, null=True)),
                ('day_of_reintroduction_antiagregant', models.IntegerField(verbose_name='Day of reintroduction anticoagulant/antiagregant', blank=True, null=True)),
                ('paris_calif', models.IntegerField(verbose_name='Paris Clasif.', blank=True, null=True, choices=[(1, '0Is'), (2, '0IIa'), (3, '0IIa+0Is'), (4, '0Is+0IIa'), (5, '0IIb'), (6, '0IIc'), (7, '0IIa+0IIc'), (8, '0IIb+0IIc'), (9, '0IIb+0IIa')])),
                ('lst_yn', models.IntegerField(verbose_name='LST yn', blank=True, null=True, choices=[(0, 'No'), (1, 'Yes')])),
                ('lst_morphology', models.IntegerField(verbose_name='LST Morphology', blank=True, null=True, choices=[(1, 'Granular homogeneous'), (2, 'Focal nodular mixed type'), (3, 'Whole nodular mixed type'), (4, 'Flat elevated'), (5, 'Psudodepressed')])),
                ('large_nodule_one_cm', models.IntegerField(verbose_name='Large nodule 1cm', blank=True, null=True, choices=[(0, 'No'), (1, 'Yes')])),
                ('demacrated_depressed_area', models.IntegerField(verbose_name='Demacrated depressed area', blank=True, null=True, choices=[(0, 'No'), (1, 'Yes')])),
                ('sclerous_wall_change', models.IntegerField(verbose_name='Sclerous wall change', blank=True, null=True, choices=[(0, 'No'), (1, 'Yes')])),
                ('fold_convergency', models.IntegerField(verbose_name='Fold convergency', blank=True, null=True, choices=[(0, 'No'), (1, 'Yes')])),
                ('chicken_skin_mucosa_around', models.IntegerField(verbose_name='Chicken skin mucosa around', blank=True, null=True, choices=[(0, 'No'), (1, 'Yes')])),
                ('maximum_size_mm', models.IntegerField(verbose_name='Maximum size (mm)', blank=True, null=True)),
                ('area_square_cm', models.IntegerField(verbose_name='Area (cm2)', blank=True, null=True)),
                ('location', models.IntegerField(verbose_name='Location', blank=True, null=True, choices=[(1, 'Rectum'), (2, 'Left colon'), (3, 'Splenic flexure'), (4, 'Transverse'), (5, 'Hepatic'), (6, 'Ascendent'), (7, 'Cecum')])),
                ('ileocecal_valve_involvement', models.IntegerField(verbose_name='Ileocecal valve involvement', blank=True, null=True, choices=[(0, 'No'), (1, 'Yes')])),
                ('high_definition', models.IntegerField(verbose_name='High definition', blank=True, null=True, choices=[(1, 'Conventional endoscope'), (2, 'High definition'), (3, 'Optic magnification')])),
                ('endoscopemodel', models.CharField(verbose_name='Endoscope model', blank=True, null=True, max_length=50)),
                ('nbi', models.IntegerField(verbose_name='NBI', blank=True, null=True, choices=[(0, 'No'), (1, 'Yes')])),
                ('nbi_sano', models.IntegerField(verbose_name='NBI sano', blank=True, null=True, choices=[(1, 'I'), (2, 'II'), (3, 'IIIA'), (4, 'IIIB')])),
                ('nbi_nice', models.IntegerField(verbose_name='NBI NICE', blank=True, null=True, choices=[(1, 'Type 1'), (2, 'Type 2'), (3, 'Type 3')])),
                ('cromoendoscopy', models.IntegerField(verbose_name='Cromoendoscopy', blank=True, null=True, choices=[(0, 'No'), (1, 'Yes')])),
                ('kudo', models.IntegerField(verbose_name='Kudo', blank=True, null=True, choices=[(1, 'I'), (2, 'II'), (3, 'IIIS'), (4, 'IIIL'), (5, 'IV'), (6, 'V-I'), (7, 'V-N')])),
                ('prepathologic_endoscopic_diagnostic_a', models.IntegerField(verbose_name='Prepathologic endoscopic diagnost 1', blank=True, null=True, choices=[(1, 'Adenoma'), (2, 'Serrated')])),
                ('prepathologic_endoscopic_diagnostic_b', models.IntegerField(verbose_name='Prepathologic endoscopic diagnost 2', blank=True, null=True, choices=[(1, 'NodisplasiaToSuperficial submucosal carcinoma'), (2, 'Deep submucosal carcinoma')])),
                ('correct_dx_adenoma_serrated', models.IntegerField(verbose_name='Correct Dx Adenoma Serrated', blank=True, null=True, choices=[(0, 'No'), (1, 'Yes')])),
                ('correct_dx_invasion', models.IntegerField(verbose_name='Correct Dx Invasion', blank=True, null=True, choices=[(0, 'No'), (1, 'Yes')])),
                ('histology', models.IntegerField(verbose_name='Histology', blank=True, null=True, choices=[(1, 'Adenoma'), (2, 'HGD-intraepitelial carcinoma in adenoma'), (3, 'Intramucosal carcinoma in adenoma'), (4, 'Superficial submucosal carcinoma in adenoma'), (5, 'Deep submucosal carcinoma in adenoma'), (6, 'Hyperplastic'), (7, 'Sesil Serrated polyp'), (8, 'Traditional Serrated Adenoma'), (9, 'Polyp Serrated Mixed or serrated polyp with dysplasia'), (10, 'Intraepitelial carcinoma Any serrated'), (11, 'Intramucosal carcinoma Any serrated'), (12, 'Superficial submucosa carc. Any serrated'), (13, 'Deep submucosa carc. Any serrated'), (14, 'Carinoid')])),
                ('histol_simplified', models.IntegerField(verbose_name='Histology simplified', blank=True, null=True, choices=[(1, 'Adenoma'), (2, 'HGD-Imucosal'), (3, 'Invasive adenoma'), (4, 'Serrated'), (5, 'HGD-Imucosal serrated'), (6, 'Invasive serrated'), (7, 'Carcinoid')])),
                ('time_of_procedure_in_mins', models.IntegerField(verbose_name='Time of procedure (m)', blank=True, null=True)),
                ('difficulty_of_emr', models.IntegerField(verbose_name='Dificutly of EMR', blank=True, null=True, choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Difficult')])),
                ('accesibility', models.IntegerField(verbose_name='Accesibility', blank=True, null=True, choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Difficult')])),
                ('resection', models.IntegerField(verbose_name='Resection', blank=True, null=True, choices=[(1, 'Piecemeal complete'), (2, 'Piecemeal incomplete'), (3, 'En bloc R0'), (4, 'En bloq incomplete')])),
                ('previous_biopsy', models.IntegerField(verbose_name='Previous biopsy', blank=True, null=True, choices=[(0, 'No'), (1, 'Yes')])),
                ('previous_attempt', models.IntegerField(verbose_name='Previous attempt', blank=True, null=True, choices=[(0, 'No'), (1, 'Yes')])),
                ('non_lifting_sign', models.IntegerField(verbose_name='Non lifting sign', blank=True, null=True, choices=[(0, 'No'), (1, 'Yes')])),
                ('technique', models.IntegerField(verbose_name='Technique', blank=True, null=True, choices=[(1, 'EMR'), (2, 'Hybrid-EMR')])),
                ('technique_two', models.IntegerField(verbose_name=' Technique 2', blank=True, null=True, choices=[(1, 'One-step'), (2, 'Two-steps')])),
                ('limit_marks', models.IntegerField(verbose_name='Limit marks', blank=True, null=True, choices=[(0, 'No marks'), (1, 'APC marks')])),
                ('injection', models.IntegerField(verbose_name='Injection', blank=True, null=True, choices=[(0, 'No'), (1, 'Saline'), (2, 'Glicerin'), (3, 'Hyaluronic'), (4, 'Hidrox-propil-cellulose: VOLUVEN(r)'), (5, 'Gelafundin'), (6, 'Others')])),
                ('adrenaline', models.IntegerField(verbose_name='Adrenaline', blank=True, null=True, choices=[(0, 'No'), (1, 'Yes')])),
                ('endocut', models.IntegerField(verbose_name='Endocut/Blended', blank=True, null=True, choices=[(1, 'Only cut current'), (2, 'Only coagulation current'), (3, 'Endocut/Blended')])),
                ('electrosurgical_generator_model', models.CharField(verbose_name='Electrosurgical generator model', blank=True, null=True, max_length=100)),
                ('polyp_retrieval', models.IntegerField(verbose_name='Polyp retrieval', blank=True, null=True, choices=[(1, 'Roth net'), (2, 'By aspiration'), (3, 'Both methods'), (4, 'By snare')])),
                ('argon_PC', models.IntegerField(verbose_name='Argon PC', blank=True, null=True, choices=[(0, 'No'), (1, 'Yes: incomplete resection'), (2, 'Yes: coagulation'), (3, 'Yes: per protocol')])),
                ('coagulation_forceps', models.IntegerField(verbose_name='Coagulation forceps', blank=True, null=True, choices=[(0, 'No'), (1, 'Yes')])),
                ('snare_tip_soft_coagulation', models.IntegerField(verbose_name='Snare tip soft coagulation', blank=True, null=True, choices=[(0, 'No'), (1, 'Yes')])),
                ('cs_cut_watts', models.IntegerField(verbose_name='Cut (watts)', blank=True, null=True)),
                ('cs_cut_mode', models.IntegerField(verbose_name='Endocut mode', blank=True, null=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')])),
                ('cs_coagulation_watts', models.IntegerField(verbose_name='Coagulation (watts)', blank=True, null=True)),
                ('cs_coagulation_mode', models.IntegerField(verbose_name='Coagulation mode', blank=True, null=True, choices=[(0, 'Soft'), (1, 'Force')])),
                ('clips_control_group', models.IntegerField(verbose_name='Clips control group', blank=True, null=True, choices=[(0, 'No'), (1, 'Punctual coagulation')])),
                ('clips_tratment_group', models.IntegerField(verbose_name='Clips treatment group', blank=True, null=True, choices=[(1, 'Complete closure with complete mucosal apposition'), (2, 'Complete closure without complete mucosal apposition'), (3, 'Total failed closure'), (4, 'Partial failed closure'), (5, 'Closure not tried')])),
                ('clips_n_lote', models.IntegerField(verbose_name='Lot number', blank=True, null=True)),
                ('clips_exp_date', models.DateField(verbose_name='Expiration date', blank=True, null=True)),
                ('not_tired_closure_by', models.IntegerField(verbose_name='Closure not tried because of', blank=True, null=True, choices=[(1, 'Big size'), (2, 'Difficult location'), (3, 'Both')])),
                ('closure_technique', models.IntegerField(verbose_name='Closure technique', blank=True, null=True, choices=[(1, 'Simple clipping'), (2, 'Clip-Poly loop'), (3, 'Clip Silk loop')])),
                ('number_clips_needed', models.IntegerField(verbose_name='Number of clips needed', blank=True, null=True)),
                ('perforation', models.IntegerField(verbose_name='Perforation', blank=True, null=True, choices=[(0, 'No'), (1, 'Yes: endoscopic resolution'), (2, 'Yes: surgical resolution')])),
                ('surgery_from_endoscopy', models.IntegerField(verbose_name='Surgery from endoscopy', blank=True, null=True, choices=[(0, 'No'), (1, 'Yes')])),
                ('surgery_by_complication', models.IntegerField(verbose_name='Surgery by complication', blank=True, null=True, choices=[(0, 'No'), (1, 'Yes: bleeding'), (2, 'Yes: perforation')])),
                ('bleeding', models.IntegerField(verbose_name='Bleeding', blank=True, null=True, choices=[(0, 'No'), (1, 'During no clinical impact-autol'), (2, 'During exploration with clinical impact'), (3, '24h'), (4, '24-48h'), (5, '3-7 days'), (6, '>7 days')])),
                ('immediate_bleeding', models.IntegerField(verbose_name='Immediate bleeding', blank=True, null=True, choices=[(0, 'No'), (1, 'Yes: during exploration with clinical impact'), (2, 'Yes: during exploration without clinical impact')])),
                ('delayed_bleeding', models.IntegerField(verbose_name='Delayed bleeding', blank=True, null=True, choices=[(0, 'No'), (1, 'Yes')])),
                ('bleeding_treatment', models.IntegerField(verbose_name='Bleeding treatment', blank=True, null=True, choices=[(0, 'No'), (1, 'Inyection'), (2, 'Clipping'), (3, 'ArgonPC'), (4, 'Coagulation forceps'), (5, '2 methods')])),
                ('transfusion', models.IntegerField(verbose_name='Transfusion', blank=True, null=True, choices=[(0, 'No'), (1, 'Yes')])),
                ('pps', models.IntegerField(verbose_name='Post polypectomy syndrome', blank=True, null=True, choices=[(0, 'No'), (1, 'Yes')])),
                ('fever', models.IntegerField(verbose_name='Fever', blank=True, null=True, choices=[(0, 'No'), (1, '37-37.9'), (2, '38 or more')])),
                ('pain_requiring_medical_intervention', models.IntegerField(verbose_name='Pain requiring medical intervantion', blank=True, null=True, choices=[(0, 'No'), (1, 'Yes')])),
                ('hospital_stay_by_technique', models.IntegerField(verbose_name='Hospital stay by technique', blank=True, null=True)),
                ('hospital_stay_by_complication', models.IntegerField(verbose_name='Hospital stay by complication', blank=True, null=True)),
                ('follow_up_months', models.IntegerField(verbose_name='Follow up months', blank=True, null=True)),
                ('successful_treatment', models.IntegerField(verbose_name=' Successful treatment', blank=True, null=True, choices=[(0, 'No: surgical treatment'), (1, 'Yes: in 1 session (includes one or two steps'), (2, 'Yes, in 2 or more sessions (one session and treatment in controls')])),
                ('sedation', models.IntegerField(verbose_name='Sedation', blank=True, null=True, choices=[(0, 'Without sedation'), (1, 'By gastroenterologist other than Propofol'), (2, 'By gastroenterologist based on Propofol'), (3, 'By anesthesiologist')])),
                ('last_date_endoscopic_follow_up', models.DateField(verbose_name='Last date endoscopic follow up', blank=True, null=True)),
                ('recurrence_three_six_months_control', models.IntegerField(verbose_name='Recurrence 3-6 months control', blank=True, null=True, choices=[(0, 'No'), (1, 'Yes: positive biopsy: endoscopic treatment'), (2, 'Yes: visible recurrence: endoscopic treatment'), (3, 'Yes: surgical treatment needed')])),
                ('recurrenec_one_year_control', models.IntegerField(verbose_name='Recurrence 1 year control', blank=True, null=True, choices=[(0, 'No'), (1, 'Yes: positive biopsy: endoscopic treatment'), (2, 'Yes: visible recurrence: endoscopic treatment'), (3, 'Yes: surgical treatment needed')])),
                ('global_recurrence', models.IntegerField(verbose_name='Global recurrence', blank=True, null=True, choices=[(0, 'No'), (1, 'Yes')])),
                ('other_complications_comments', models.TextField(verbose_name='Other complications comments', blank=True, null=True, max_length=500)),
                ('other_comments', models.TextField(verbose_name='Other comments', blank=True, null=True, max_length=500)),
                ('doctor', models.ForeignKey(verbose_name='Doctor', blank=True, null=True, to='studies_app.UserProfile')),
                ('hospital', models.ForeignKey(default=None, null=True, to='studies_app.Hospital', blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='clipscase',
            name='hb',
            field=models.FloatField(verbose_name='HB (g/dL)', blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clipscase',
            name='platelets',
            field=models.IntegerField(verbose_name='Platelets (x10⁹/L)', blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clipscase',
            name='pt',
            field=models.IntegerField(verbose_name='PT (s)', blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='study_type',
            field=models.CharField(verbose_name='Study type', max_length=64, choices=[('clips', 'Clips Study'), ('cancer', 'Cancer Study'), ('observational', 'Observational Study')]),
        ),
        migrations.AddField(
            model_name='observationalcase',
            name='study',
            field=models.ForeignKey(verbose_name='Study', to='studies_app.Study', related_name='cases_observationalcase'),
        ),
    ]
